### ISSUE TITLE
Further refactoring - replace hardcoded button, row, col handling

### ISSUE THREAD

**Issue by stuaxo** [steve-shambles/Bletchley#7]
The next stage in reducing repetition will be to replace all the buttons and row handling that is hardcoded to particular rows columns with something more general that works on a data structure.

**Comment by stuaxo** [comment]
I it looks like you could replace all the classes like 

button_up_row1

With something like

button_up_row1 = namedtuple(put vars here)


Not much detail as reporting by phone, but go read how to use namedtuple.



These functions like clk_but_1_3 could be improved for readability, what is s1 here?

Why is what looks like a temp variable global ?



Hope this mares sense, I haven't run the code yet. 

In general, for the functions and classes that have *almost* the same content, go through them one by one and see if you can come up with code that is more general to replace them.

**Comment by stuaxo** [comment]
outcome looks like it doesn't need to be a class, you could probably replace it with a function.

**Comment by steve-shambles** [comment]
Hi Stuaxo.
CMsteffan is working on all that stuff (luckily for me) 
because I'm struggling with that stuff at the moment.

**Comment by stuaxo** [comment]
@steve-shambles it becomes easier with experience :)

**Comment by stuaxo** [comment]
Hopefully you'll still understand the code after it's refactored (at least, you can see  the difference) and that'll help you when you hit the same things in future.

The first few months I knew python I used it so little the only loop I knew was a ```while``` loop, and that got me through.

**Comment by steve-shambles** [comment]
> 
> 
> Hopefully you'll still understand the code after it's refactored (at least, you can see the difference) and that'll help you when you hit the same things in future.
> 
> The first few months I knew python I used it so little the only loop I knew was a `while` loop, and that got me through.

You are right, I love what Steff has done with the music module, (includes some of your suggestions, thanks)  I never realised how simple it is to make separate modules and import them, just never felt the need but now I see it is very useful when done properly.

Also Steff uses a simple class that doesn't scare me in the least,  I would even  venture to say, I get it!

**Comment by cmsteffen-code** [comment]
I definitely plan to refactor the code in this exact way, removing all repetitive functions and using loops.

I also plan to employ extensive comments, so that it's as simple as possible to understand what I'm doing. :smile:

**Comment by stuaxo** [comment]
Great, it's looking much improved.

Having a quick look, list creation, access and iteration is something that stands out now:

A lot of the time 'index' is a row/column so should probably be named as such.


Some of the time 'index' can be removed by iterating the items in a list instead (or if both the item AND an index is needed look at enumerate) 


Named constants should probably be used for amount of columns rows instead of magic numbers like 5 and 6.



Misc


Having stuff like BUTTON in all caps when looks a bit weird.



Not much time to look at this now, but definitely more stuff, especially around buttons.

**Comment by stuaxo** [comment]
Does new_game need to destroy all widgets?

I'd guess per game stuff is separate to things like music etc

**Comment by steve-shambles** [comment]
The only thing I can think of adding to the game now is proper graphics for the pegs (round and shiny) and the outcomes on the yellow labels.  That's way out of my league graphicly and programmatically, so I doubt that will happen.  That being the case this is the complete game and just needs further play testing and checked on Linux and Mac for compatibility.  Thanks Stu and Steff for your help.

**Comment by steve-shambles** [comment]
> 
> 
> @steve-shambles you're pretty lucky, you'll shortcut months of learning by seeing these changes and understanding them :D

yes, it took me over a week to understand Steff's code, still only fully understand about 50% of it really, but I have learnt a hell of a lot from it.
